apiVersion: v1
kind: Pod
metadata:
  name: db-pod-secret
spec:
  containers:
  - name: db-pod-secret
    image: alpine
    command: 
    - sleep
    - 1d
    envFrom:
    - secretRef:
        name: db-secret  